name: ci-cd
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Install Dependencies
              run: npm install
            - name: Test Project
              run: npm test
    build:
        # TODO: Make build depend on test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            - name: Install Dependencies
              run: npm install
            - name: Build Project
              run: npm run build
            - name: Upload artefact
              uses: actions/upload-artifact@v3
              with:
                name: production-files
                path: ./build
    deploy:
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        # if: github.ref == 'ref/heads/master'
        steps:
            - name: Download artefact
              uses: actions/download-artifact@v3
              with:
                name: production-files
                path: ./build
            - name: Deploy to GitHub pages
              uses: actions/deploy-pages@4